pipeline {
    agent any
    triggers {
        githubPush()    // 🔥 Trigger Jenkins on every push to repo
    }

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
                sh 'ls -a'
            }
        }
        stage('branch test'){
            when { branch 'feature/2025.11.19' }
            steps {
                echo "hello world new"
                dir('day3-code') {
               // git url: 'https://github.com/redashu/terraform_BOA_test.git', branch: 'master'
                sh 'ls -a'
            }
        }
        stage('terraform test'){
            when {
                 expression { env.BRANCH_NAME == 'feature/2025.11.19' || env.GIT_BRANCH == 'origin/feature/2025.11.19' }
            }   
            steps {
                echo "hello world new data"
                dir('day3-code') {
                    sh 'terraform init'
                }
            // git url: 'https://github.com/redashu/terraform_BOA_test.git', branch: 'dev'
                dir('day3-code') {
                    sh 'terraform plan'
                }
            }
        }
    }
}